# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'vs2017-win2016'

variables:
  buildConfiguration: 'Release'
  aspWebDir: '$(Build.SourcesDirectory)/aspnet-core/src/SavageRule.Web.Host/'
  ngDir: '$(Build.SourcesDirectory)/ng/'

steps:
- task: NodeTool@0 
  inputs:
    versionSpec: '9.x'

- script: dotnet build ${hostProject} --configuration $(buildConfiguration)
  displayName: Build Host
  workingDirectory: ${aspWebDir}